# Generated by Django 4.1.7 on 2023-03-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(default='To be added', max_length=1000)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
